image: cirrusci/flutter:stable

before_script:
  - flutter pub get

stages:
  - build
  - analyze

build:
  stage: build
  script:
    - flutter build apk

analyze:
  stage: analyze
  script:
    - flutter analyze